##################
# Notif to email #
##################
global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'prometheus@server.corpX.un'
  smtp_require_tls: false
  #smtp_auth_username: 'xxx@xxxx.com'
  #smtp_auth_password: 'xxxxxx'

route:
  group_by: ['notif']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: devops

  routes:
    - match:
        severity: critical
      receiver: devops

receivers:
- name: 'devops'
  email_configs:
 # - to: 'destination@localhost.com'
  #send_resolved: true
